Задание 2-1
VladimirKruglov/-Procedural-programming pull request #13
Opened 2021-04-19 17:42 UTC by VladimirKruglov

2021-04-20 09:24 UTC, MarinaPaley requested changes
Все хорошо, только задача на использование класса перечисления `class enum`

2021-04-20 09:24 UTC, MarinaPaley commented on Task_2-1/main.cpp
> +double calcVolume(double lentgh, double width, double height);
Nit: `GetVolume`

2021-04-20 09:24 UTC, MarinaPaley commented on Task_2-1/main.cpp
> +* \brief Функция, высчитывающая объем параллелепипеда
Nit: рассчитываюшая

2021-04-23 10:21 UTC, MarinaPaley requested changes
Перечислимый тип есть, но не используется

2021-04-23 10:21 UTC, MarinaPaley commented on Task_2-1/main.cpp
> +#include <Windows.h>
Зачем?

2021-04-23 11:23 UTC, VladimirKruglov commented on Task_2-1/main.cpp
> +#include <Windows.h>
Как я понял с помощью файла <Windows.h> у меня корректно отображаются и вводятся символы кириллицы

2021-04-23 11:23 UTC, VladimirKruglov commented on Task_2-1/main.cpp
> +#include <Windows.h>
Как я понял с помощью файла <Windows.h> у меня корректно отображаются и вводятся символы кириллицы

2021-05-12 13:14 UTC, MarinaPaley approved these changes

2021-05-12 17:19 UTC, merged