Выполнил задание 1-1.
VladimirKruglov/-Procedural-programming pull request #3
Opened 2021-03-31 12:35 UTC by VladimirKruglov

2021-04-02 17:11 UTC, MarinaPaley requested changes
1. Блок-схема... она подходит для всех задач 🤦 
2. Валидация. Объясните, почему знаки разные?
3. А где файлы проекта и т.д. Как Вы работаете в C++?

2021-04-02 17:11 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +#define USE_MATH_DEFINER
порядок важен: сначала `define`потом `cmath`

2021-04-02 17:11 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +double GetA(const double x, const double y, const double z) {
добавьте документацию для всех методов

2021-04-02 17:11 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +	const auto a = -GetA(x, y, z);
зачем минус?

2021-04-02 17:11 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +		<< "y = " << y << endl
`endl` прерывает выполнение команд и СРОЧНО опустошает поток ввода\вывод. Лучше "накапливать" то, что потом выведется в консоль (или другой поток), использовать '\n`, а в конце уже использовать `endl` - явно опустошив поток ввода\вывода

2021-04-03 10:40 UTC, VladimirKruglov commented on Task_1-1/main.cpp
> +	const auto a = -GetA(x, y, z);
Потому что появилась такая проблема, что нельзя найти корень из отрицательного числа (даже если это корень 3-ей степени), поэтому приходится брать подкоренное значение в модуль и потому добавлять минус.

2021-04-03 12:41 UTC, MarinaPaley commented
![image](https://user-images.githubusercontent.com/26978698/113478672-f0bd3580-9492-11eb-8340-e69079da6610.png)
Если просите посмотреть еще раз, иначе никогда не узнаю

2021-04-03 17:18 UTC, MarinaPaley requested changes
Сто́ит продолжить вносить изменения.

2021-04-03 17:18 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +#define USE_MATH_DEFINER
Математическая константа, которую Вы подразумеваете, называется _иначе_ &ndash; [`_USE_MATH_DEFINES`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-160).

2021-04-03 17:18 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +double GetA(const double x, const double y, const double z) {
Стоит разделить работу с методами на объявление (_декларацию_) и реализацию методов. Например, так:
```cpp
// ...

/**
 * \brief Демонстрационная функция.
 * \param argument Аргумент функции.
 * \return Ответ на главный вопрос Вселенной и всего такого.
 */
double my_method(const double argument);

// ...

/**
 * \brief Точка входа в программу.
 * \return Код ошибки (0 - успех).
 */
int main()
{
    // ...

   auto result = my_method(0);

    // ...

    return 0;
}

// ...

double my_method(const double argument)
{
    return 42;
}

2021-04-04 16:54 UTC, VladimirKruglov commented
> 1. Блок-схема ... она подходит для всех задач 🤦
> 2. Валидация. Объясните, почему знаки разные?
> 3. А где файлы проекта и т.д. Как Вы работаете в C ++?

![картинка](https://user-images.githubusercontent.com/80893929/113515825-6f8f9c80-957f-11eb-9958-1cbfe2622a8c.png)
Вот эти файлы?

2021-04-11 13:45 UTC, VladimirKruglov commented on Task_1-1/main.cpp
> +double GetA(const double x, const double y, const double z) {
Добавил

2021-04-12 14:48 UTC, VladimirKruglov commented on Task_1-1/main.cpp
> +		<< "y = " << y << endl
Изменил

2021-04-12 14:49 UTC, VladimirKruglov commented on Task_1-1/main.cpp
> +	const auto a = -GetA(x, y, z);
Сделано

2021-04-14 12:22 UTC, MarinaPaley requested changes
Реализация отдельно от объявления
Измените документацию

2021-04-14 12:42 UTC, MarinaPaley approved these changes
Подправить закоммитеть, можно merge

2021-04-14 12:42 UTC, MarinaPaley commented on Task_1-1/main.cpp
> +* \brief Математическая функция, рассчитывающая значение b
в данном случае можно без конкретики, тем более, что сделали ошибку ( `b`)

2021-04-14 19:00 UTC, merged